"""POC settings loaded from environment variables."""

from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv

ROOT_DIR = Path(__file__).resolve().parents[1]
load_dotenv(ROOT_DIR / ".env")

OUTPUT_DIR = ROOT_DIR / os.getenv("POC_OUTPUT_DIR", "outputs")
EXECUTION_TIMEOUT_SECONDS = int(os.getenv("POC_EXECUTION_TIMEOUT_SECONDS", "60"))
DESIGN_TIMEOUT_SECONDS = int(os.getenv("POC_DESIGN_TIMEOUT_SECONDS", "900"))
EXECUTE_REF_TIMEOUT_SECONDS = int(os.getenv("POC_EXECUTE_REF_TIMEOUT_SECONDS", "90"))
AI_STEP_TIMEOUT_SECONDS = int(os.getenv("POC_AI_STEP_TIMEOUT_SECONDS", "300"))

GENERATOR_MODEL = os.getenv("GENERATOR_MODEL", "fixture")
JUDGE_MODEL = os.getenv("JUDGE_MODEL", "fixture")
SOLVER_MODEL = os.getenv("SOLVER_MODEL", "fixture")
REPAIR_MODEL = os.getenv("REPAIR_MODEL", "fixture")
MODEL_PROVIDER = os.getenv("MODEL_PROVIDER", "fixture")

OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "").rstrip("/")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "llama3.1:8b")
OLLAMA_CF_ACCESS_CLIENT_ID = os.getenv("OLLAMA_CF_ACCESS_CLIENT_ID", "")
OLLAMA_CF_ACCESS_CLIENT_SECRET = os.getenv("OLLAMA_CF_ACCESS_CLIENT_SECRET", "")
OLLAMA_TIMEOUT_SECONDS = int(os.getenv("OLLAMA_TIMEOUT_SECONDS", "120"))
OLLAMA_JSON_RETRIES = int(os.getenv("OLLAMA_JSON_RETRIES", "1"))
OLLAMA_NUM_CTX = int(os.getenv("OLLAMA_NUM_CTX", "4096"))
OLLAMA_MCQ_NUM_PREDICT = int(os.getenv("OLLAMA_MCQ_NUM_PREDICT", "1400"))
OLLAMA_PBQ_NUM_PREDICT = int(os.getenv("OLLAMA_PBQ_NUM_PREDICT", os.getenv("OLLAMA_CODING_NUM_PREDICT", "4200")))

OPENAI_BASE_URL = os.getenv("OPENAI_BASE_URL", "https://api.openai.com/v1").rstrip("/")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
OPENAI_ORGANIZATION = os.getenv("OPENAI_ORGANIZATION", "")
OPENAI_PROJECT = os.getenv("OPENAI_PROJECT", "")
OPENAI_TIMEOUT_SECONDS = int(os.getenv("OPENAI_TIMEOUT_SECONDS", str(OLLAMA_TIMEOUT_SECONDS)))
OPENAI_MAX_COMPLETION_TOKENS = int(os.getenv("OPENAI_MAX_COMPLETION_TOKENS", str(OLLAMA_PBQ_NUM_PREDICT)))

# Staged PBQ generation (LangGraph pipeline)
PBQ_STAGED_GENERATION = os.getenv("PBQ_STAGED_GENERATION", "1") == "1"
PBQ_STAGE_FEATURE_PLAN_TOKENS = int(os.getenv("PBQ_STAGE_FEATURE_PLAN_TOKENS", "1500"))
PBQ_STAGE_QUESTION_SPEC_TOKENS = int(os.getenv("PBQ_STAGE_QUESTION_SPEC_TOKENS", "1200"))
PBQ_STAGE_REFERENCE_FILE_TOKENS = int(os.getenv("PBQ_STAGE_REFERENCE_FILE_TOKENS", "2000"))
PBQ_STAGE_STARTER_FILE_TOKENS = int(os.getenv("PBQ_STAGE_STARTER_FILE_TOKENS", "1500"))
PBQ_STAGE_PUBLIC_TESTS_TOKENS = int(os.getenv("PBQ_STAGE_PUBLIC_TESTS_TOKENS", "1500"))
PBQ_STAGE_PRIVATE_TESTS_TOKENS = int(os.getenv("PBQ_STAGE_PRIVATE_TESTS_TOKENS", "1500"))
PBQ_STAGE_MUTATIONS_TOKENS = int(os.getenv("PBQ_STAGE_MUTATIONS_TOKENS", "1200"))
PBQ_STAGE_FILE_REPAIR_MAX = int(os.getenv("PBQ_STAGE_FILE_REPAIR_MAX", "2"))
PBQ_STAGE_FILE_TIMEOUT_SECONDS = int(os.getenv("PBQ_STAGE_FILE_TIMEOUT_SECONDS", "90"))
